import React from 'react'

export default function Head() {
  return (
    <React.Fragment>
      <title>House</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="description" content="Generated by rineta.io" />
    </React.Fragment>
  )
}